import { Member } from "@/types";

const mock: Member[] = [
    {
        id: 1,
        name: "김사자",
        major: "인공지능학과",
        position: "프론트엔드",
        userTags: ["프론트엔드", "아기사자"],
        profileIntro: "안녕하시렵니까",
        profileIntroTags: ["위엄", "라잌어", "라이옹"],
        profileIntroSkills: ["잠자기", "공부하기"],
        profileExternalLinks: [
            { label: "GitHub", url: "https://github.com" },
            { label: "Portfolio", url: "https://portfolio.com" },
        ],
        imageUrl: "/static/images/placeholder.png",
        role: "아기사자",
    },
    {
        id: 2,
        name: "김어흥",
        major: "인공지능학과",
        position: "프론트엔드",
        userTags: ["프론트엔드", "운영진", "홍보부"],
        profileIntro: "안녕하시렵니까",
        profileIntroTags: ["위엄", "라잌어", "라이옹"],
        profileIntroSkills: ["잠자기", "공부하기"],
        profileExternalLinks: [
            { label: "GitHub", url: "https://github.com" },
            { label: "Portfolio", url: "https://portfolio.com" },
        ],
        imageUrl: "/static/images/placeholder.png",
        role: "운영진",
    },
    {
        id: 3,
        name: "김야옹",
        major: "시각디자인학과",
        position: "프론트엔드",
        userTags: ["프론트엔드", "아기사자"],
        profileIntro: "안녕하시렵니까",
        profileIntroTags: ["위엄", "라잌어", "라이옹"],
        profileIntroSkills: ["잠자기", "공부하기"],
        profileExternalLinks: [
            { label: "GitHub", url: "https://github.com" },
            { label: "Portfolio", url: "https://portfolio.com" },
        ],
        imageUrl: "/static/images/placeholder.png",
        role: "아기사자",
    },
    {
        id: 4,
        name: "김호랭",
        major: "컴퓨터공학과",
        position: "백엔드",
        userTags: ["백엔드", "운영진", "학술부"],
        profileIntro: "안녕하시렵니까",
        profileIntroTags: ["위엄", "라잌어", "라이옹"],
        profileIntroSkills: ["잠자기", "공부하기"],
        profileExternalLinks: [
            { label: "GitHub", url: "https://github.com" },
            { label: "Portfolio", url: "https://portfolio.com" },
        ],
        imageUrl: "/static/images/placeholder.png",
        role: "운영진",
    },
    {
        id: 5,
        name: "김뀨뀨",
        major: "인공지능학과",
        position: "AI",
        userTags: ["AI", "아기사자"],
        profileIntro: "안녕하시렵니까",
        profileIntroTags: ["위엄", "라잌어", "라이옹"],
        profileIntroSkills: ["잠자기", "공부하기"],
        profileExternalLinks: [
            { label: "GitHub", url: "https://github.com" },
            { label: "Portfolio", url: "https://portfolio.com" },
        ],
        imageUrl: "/static/images/placeholder.png",
        role: "아기사자",
    },
];

export default mock;
