export const newsMock = [
    {
        id: "1",
        date: "2025.04.18",
        title: "첫번째 정기세션",
        description: "기대와 설렘 속에 시작된 첫 세션! 드디어 멋사 13기의 첫걸음을 내디뎠습니다 💪",
        thumbnailUrl: "/static/images/placeholder.png",
    },
    {
        id: "2",
        date: "2025.04.25",
        title: "워크숍: 피그마 필수 기능",
        description: "UI 디자이너를 위한 피그마 기능 워크숍이 성공적으로 진행되었습니다 🎨",
        thumbnailUrl: "/static/images/placeholder.png",
    },
    {
        id: "3",
        date: "2025.05.02",
        title: "Git/GitHub 세미나",
        description: "협업을 위한 Git/GitHub 실전 세미나가 열렸습니다. 아기사자들 모두 집중! 🧠",
        thumbnailUrl: "/static/images/placeholder.png",
    },
    {
        id: "4",
        date: "2025.05.09",
        title: "HTML/CSS 실습",
        description: "기초부터 차근차근! 웹개발의 기본을 실습으로 익혔습니다 🧱",
        thumbnailUrl: "/static/images/placeholder.png",
    },
    {
        id: "5",
        date: "2025.05.16",
        title: "프로젝트 중간 점검",
        description: "각 팀의 첫 프로젝트가 본격적으로 시작되었어요! 🔍",
        thumbnailUrl: "/static/images/placeholder.png",
    },
    {
        id: "6",
        date: "2025.05.23",
        title: "미니 프로젝트 발표",
        description: "두근두근 발표의 날! 2주간의 미니 프로젝트가 마무리되었습니다 🎤",
        thumbnailUrl: "/static/images/placeholder.png",
    },
    {
        id: "7",
        date: "2025.05.30",
        title: "UX/UI 디자인 리뷰",
        description: "최근 작업물에 대한 UX/UI 디자인 리뷰 세션을 진행했습니다 🖌️",
        thumbnailUrl: "/static/images/placeholder.png",
    },
    {
        id: "8",
        date: "2025.06.06",
        title: "React 심화 강의",
        description: "React 훅과 상태관리 심화 강의를 통해 현업 스킬을 업그레이드했어요 ⚛️",
        thumbnailUrl: "/static/images/placeholder.png",
    },
    {
        id: "9",
        date: "2025.06.13",
        title: "팀 협업 워크샵",
        description: "효율적인 팀 협업을 위한 워크샵을 진행하여 커뮤니케이션을 다졌습니다 🤝",
        thumbnailUrl: "/static/images/placeholder.png",
    },
    {
        id: "10",
        date: "2025.06.20",
        title: "최종 프로젝트 데모데이",
        description: "모든 팀이 최종 프로젝트를 발표하는 데모데이를 성공적으로 마쳤습니다 🎉",
        thumbnailUrl: "/static/images/placeholder.png",
    },
];
