name: Deploy Storybook

on:
    push:
        branches: [main, dev]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
            NODE_OPTIONS: "--max-old-space-size=4096"
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node.js 20.19.0
              uses: actions/setup-node@v4
              with:
                  node-version: 20.19.0

            - name: Setup PNPM 10.8.0
              uses: pnpm/action-setup@v2
              with:
                  version: 10.8.0

            - name: Install dependencies
              run: pnpm install

            - name: Build Storybook
              run: pnpm build-storybook

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./storybook-static
                  destination_dir: ${{ github.ref_name == 'main' && 'storybook' || 'storybook-dev' }}
